### PR TITLE
[automated] Update Rector Dependencies

### PR DESCRIPTION
**Pull request by TomasVotruba**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Comment by samsonasik** [comment]
smoke test error seems due to manifest.json not generated

```
Illuminate\View\ViewException:\n
Vite manifest not found at: /home/abdul/www/getrector-com/bootstrap/../public/build/manifest.json (View: /home/abdul/www/getrector-com/resources/views/_snippets/styles.blade.php) (View: /home/abdul/www/getrector-com/resources/views/_snippets/styles.blade.php) (View: /home/abdul/www/getrector-com/resources/views/_snippets/styles.blade.php)\n
```

**Comment by samsonasik** [comment]
it seems working ok by update VersionResolver namespace https://github.com/rectorphp/getrector-com/pull/1901/commits/1cb094d7f7f1816ae8144b475a268da46b35abd6

**Comment by TomasVotruba** [comment]
Lets bump the website and server to PHP 8.2.
Could you upgrade it?

**Comment by samsonasik** [comment]
I will try upgrade server next week once I got more stable internet connection :+1:

**Comment by TomasVotruba** [comment]
Thanks, no rush :)

**Pull request merged**
