### PR TITLE
[Docs] Add note for withPreparedSets() on php 7.x

### PR DESCRIPTION
**Pull request by samsonasik**
On php 7.x, the named argument is not yet exists, this update doc to clarify it.

Ref https://github.com/rectorphp/rector/issues/8653
/cc @orionseye

### CODE REVIEW

**Comment by samsonasik** [comment]
Using diff for better see the different:

Screenshot 2024-05-26 at 14 44 18

**Comment by samsonasik** [comment]
Ready to merge 👍

**Comment by TomasVotruba** [comment]
I think calling the methods like this:

```php
->withPreparedSets(true, false, true, true);
```
could be a bit unreadable :) I'd recommend to use `withSets([...])` instead, untill the project is upgraded to PHP 8.

**Comment by samsonasik** [comment]
Ok, updated with `withSets()`

**Comment by TomasVotruba** [comment]
Thank you :clap:

**Pull request merged**
