### PR TITLE
Fix rule-detail 500 error

### PR DESCRIPTION
**Pull request by samsonasik**
**Before**

Screenshot 2024-07-15 at 00 42 20

**After**

Screenshot 2024-07-15 at 00 41 47

Fixes https://github.com/rectorphp/getrector-com/issues/2405
Fixes https://github.com/rectorphp/getrector-com/issues/2433

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Better use getName() in template directly. This hides object as a string

**Comment by samsonasik** [comment]
sure, updated with `->getName()` method https://github.com/rectorphp/getrector-com/pull/2431/commits/f7b36428fb8d1143b1fde231e1cad9c1fce85061

btw, I am not sure why **"Rule detail"** link is not shown in getrector.com site:

**Local:**

Screenshot 2024-07-15 at 02 58 03


**GetRector.com**

Screenshot 2024-07-15 at 02 58 56

**Comment by samsonasik** [comment]
Oh, I see, the dev mark:

https://github.com/rectorphp/getrector-com/blob/9eb620d4c38324a7fda5ab1f160d2236e06e1f08/resources/views/livewire/rector-filter-component.blade.php#L74

can it be enabled and test on production?

**Comment by samsonasik** [comment]
Also fixed invalid `use false` and `use true` https://github.com/rectorphp/getrector-com/issues/2433

**Comment by samsonasik** [comment]
Let's enable rule detail link as well so we have faster feedback https://github.com/rectorphp/getrector-com/pull/2431/commits/76c907ab50648a4ddc42d94512ed27b5ac9259ee

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Review by TomasVotruba — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thanks

**Pull request merged**
