### PR TITLE
Improving Rector Performance blog post

### PR DESCRIPTION
**Pull request by carlos-granados**
@TomasVotruba as agreed here is my blog post about Improving Rector Performance. Please take a look and let me know if there is anything that needs changing. Please also let me know once this is live. Thanks!!

### CODE REVIEW

**Comment by carlos-granados** [comment]
It seems that it is just that the file preview cannot show this properly, hopefully it will show correctly once published

**Comment by carlos-granados** [comment]
I just tested this by launching a local version of the site and everything seems to be displaying ok, so I hope everything is fine 😄

**Comment by TomasVotruba** [comment]
Looking into this :) don't worry about the file preview, I'll check it

**Comment by TomasVotruba** [comment]
I've just read it and the  post looks awesome. It explains the issue, the solution and benefits.
Nice and clear :clap:  :partying_face:

**Pull request merged**
