### PR TITLE
Use SetList::TYPE_DECLARATION in demo defaults

### PR DESCRIPTION
**Pull request by staabm**
I think for an end-user its more suprising and compelling to see rector inferring types instead of detecting/removing dead code

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hi, thanks for the proposal. Makes sense to me to show more powerful contents :+1: 

Could you share screenshot what is the submitted file result?

**Comment by staabm** [comment]
the diff will be

grafik

I was not able to run the rector demo on my machine.
it errors with "php command not found" errors. not sure why.

**Comment by TomasVotruba** [comment]
We should fix that first, so you can develop with real feedback.

The validation is triggered here: https://github.com/rectorphp/getrector-com/blob/821e48e3275bd02e327648e59f2e217c994d15ea/src/Validator/PhpLinter.php#L29-L30

It should be bare php-parser run. Where exactly is this error thrown?

**Comment by samsonasik** [comment]
@TomasVotruba php command not found is unrelated with this change, it mostly path issue setting local dev machine ( mostly due to multiple php installed and composer/symfony/daimon can't know which php installed)

**Comment by staabm** [comment]
@samsonasik can you give me a hint where this is configured, or how I can make the getrector-com project make use the correct `php` command?

**Comment by samsonasik** [comment]
@staabm I don't know, I have that issue as well locally 😄 , all I can do is pray it not break something for testing demo page 😁

**Comment by staabm** [comment]
the php-command-not-found problem is gone, but new errors are coming up. 

I was able to work arround the "failed to create temp dir error"

266045624-0611bf51-f8fa-4efc-81ef-1c8402a56e34

using

```diff
diff --git a/src/DemoRunner.php b/src/DemoRunner.php
index cb78094..02a64a3 100644
--- a/src/DemoRunner.php
+++ b/src/DemoRunner.php
@@ -78,6 +78,8 @@ final class DemoRunner

         $process = new Process([
             PHP_BINARY ,
+            '-d',
+            'sys_temp_dir='.sys_get_temp_dir(),
             // paths for phpunit differs based on test/demo, not sure why
             \defined('PHPUNIT_COMPOSER_INSTALL') ? 'vendor/bin/rector' : '../vendor/bin/rector',
             'process',
```

but now I get tcp errors

grafik

**Comment by samsonasik** [comment]
@staabm that's strange, I cannot reproduce. You may need to manually create rector_cached_files dir in C:\Windows

**Comment by staabm** [comment]
could someone of you guys test this PR and merge it if successfull. I guess the app is not working on my corporate laptop for some security/safety tooling reason

**Comment by samsonasik** [comment]
Tested locally, it seems working ok, thank you @staabm

**Review by samsonasik — APPROVED** [review]

**Comment by staabm** [comment]
Thanks!

**Comment by TomasVotruba** [comment]
:+1:

**Pull request merged**
