### PR TITLE
[Doc] Update troubleshoot parallel config enable/disable with setting config

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
I updated config to recommend use RectorConfigBuilder https://github.com/rectorphp/getrector-com/pull/2124/commits/98d78c88f4df139add983d7f7c83010acc349915

**Comment by samsonasik** [comment]
@TomasVotruba I am merging it ;)

**Comment by TomasVotruba** [comment]
LGTM :+1:

**Pull request merged**
