### PR TITLE
Utilize ArrayLookup

### PR DESCRIPTION
**Pull request by samsonasik**
I found a use case that it can be usefull for this, that can be used here to early check on search found, eg:

-  `Atleast::once()` usage on 
    - packages/Blog/Twig/RoutingTwigExtension.php
    - packages/Demo/Utils/FileDiffCleaner.php

-    `Finder::first()` usage on `packages/Blog/Repository/PostRepository.php`

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
Rebased.

**Comment by samsonasik** [comment]
@TomasVotruba mergeable?

**Comment by TomasVotruba** [comment]
Yes, lets give it run :+1:  Thanks

**Pull request merged**
