### PR TITLE
[Blog] Add blog post: 5 Tricks to Write Custom Rules

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hey, I'm looking into this... :) when do you think it's ready to ship?

**Comment by samsonasik** [comment]
I will continue today and hopefully can have review ready tomorrow 👍

**Comment by samsonasik** [comment]
Ready to merge 👍

**Comment by TomasVotruba** [comment]
I've fixed the social image preview, so you can be seen as author correctly now :+1: 

Screenshot from 2024-05-20 12-03-48

**Comment by TomasVotruba** [comment]
Good to go, thank you Abdul :clap:

**Pull request merged**
