### PR TITLE
Fix missing semicolon warning on demo config page

### PR DESCRIPTION
**Pull request by samsonasik**
@staabm this fix https://github.com/rectorphp/getrector-com/issues/2012

### CODE REVIEW

**Comment by staabm** [comment]
oh interessting. I can only verify after its deployed. 

thanks for working on it.

**Comment by samsonasik** [comment]
@TomasVotruba let's merge and deploy ;)

**Comment by samsonasik** [comment]
@staabm deployed 👍

**Comment by staabm** [comment]
looks fixed, thanks

grafik

**Pull request merged**
