### PR TITLE
[automated] Update Rector Dependencies

### PR DESCRIPTION
**Pull request by TomasVotruba**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Comment by samsonasik** [comment]
Unit test seems failure due to removed `RemovedAndAddedFilesCollector`

**Comment by TomasVotruba** [comment]
Closing as not needed now

**Comment by samsonasik** [comment]
I will check if there is solution for that 👍

**Comment by samsonasik** [comment]
https://github.com/rectorphp/getrector-com/pull/1394

**Pull request closed without merging**
