### PR TITLE
More explicit error message on invalid php code

### PR DESCRIPTION
**Pull request by staabm**
refs https://github.com/rectorphp/rector/issues/8170#issuecomment-1701087008

grafik

----

grafik

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hi, thanks for the improvement :+1: 

The error message seems unrelated to the PHP file content in the screenshots. 
Could you keep the submitted code in the input, so it makes more sense?

**Comment by samsonasik** [comment]
@TomasVotruba keeping code submitted on error seems require save code to session(flash message) to be kept to show to user

**Comment by staabm** [comment]
> keeping code submitted on error seems require save code to session(flash message) to be kept to show to user

can't we just re-render what we got via POST ?

**Comment by samsonasik** [comment]
@staabm good idea, that's should work with 303 Post Redirect Get

**Comment by TomasVotruba** [comment]
Any update on this? I'd like to finish and deploy before we jump to next issue

**Comment by staabm** [comment]
I am still not having a working version on the website on my windows machine. I did not yet try to setup one on my macbook

**Comment by samsonasik** [comment]
I will take care of it and then continue verify 100+ lines to keep code in the form.

**Comment by samsonasik** [comment]
Thank you @staabm

**Comment by TomasVotruba** [comment]
Thank you :partying_face:

**Pull request merged**
