### PR TITLE
[automated] Update Rector Dependencies

### PR DESCRIPTION
**Pull request by TomasVotruba**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Comment by samsonasik** [comment]
It seems there is error:

```


There was 1 error:

1) Rector\Website\Utils\Tests\Rector\Rector\ClassMethod\SymfonyRouteAttributesToLaravelRouteFileRector\SymfonyRouteAttributesToLaravelRouteFileRectorTest::test
Rector\Core\Exception\ShouldNotHappenException: Look at "Rector\Website\Utils\Rector\Rector\ClassMethod\SymfonyRouteAttributesToLaravelRouteFileRector::resolveRouteTaret()" on line 131

/home/runner/work/getrector-com/getrector-com/utils/Rector/Rector/ClassMethod/SymfonyRouteAttributesToLaravelRouteFileRector.php:131
```

I will check.

**Comment by samsonasik** [comment]
It seems due to parent attribute usage, which now got null:

https://github.com/rectorphp/getrector-com/blob/cc7c1b478b0143d2ad165df7ecf9e1277ab609be/utils/Rector/Rector/ClassMethod/SymfonyRouteAttributesToLaravelRouteFileRector.php#L129-L132

due to PR:

- https://github.com/rectorphp/rector-src/pull/4841

**Comment by samsonasik** [comment]
Fixed with use `Class_` node .

**Comment by TomasVotruba** [comment]
:+1:  These rules can be now deleted, they were only temporary for this website migration

**Pull request merged**
